### ISSUE TITLE
«Дефолт» в отчётах

### ISSUE THREAD

**Issue by vdv73rus** [Restream/obeder#18]
В печатной версии не выводить весь офигевший список еды тем, кто ест дефолтный набор, а просто писать «Дефолт».

**Comment by LionsHead** [comment]
А в печатной версии где-то вообще написано что идет по-дефолту? Или это проблемы повара?

**Comment by vdv73rus** [comment]
@LionsHead ну вверху просто описать дефолт одной строкой
