### ISSUE TITLE
Пользователю добавляются дубликаты блюд

### ISSUE THREAD

**Issue by snop-snov** [Restream/obeder#24]
примерный кейс для воспроизведения
[14/03/2017, 23:01:16] Dmitry Makarov: попробуйте выбрать блюда, ткнуть в сброс и еще раз на те же ткнуть

**Comment by mkalmykov** [comment]
В явном виде дублирование не воспроизвелось, но установлено, что нажатие на кнопку "Сбросить" не удаляет блюдо из списка выбранных пользователем.

**Comment by mkalmykov** [comment]
Выяснили с @defrid, что блюдо не удалялось, потому что был неполный кейс.

**Comment by mkalmykov** [comment]
Кейс для воспроизведения:
1. Добавить пользователя.
2. Добавить блюда: 2 супа, 2 салата, 2 самостоятельных блюда.
3. В каждой паре блюд сделать одно из блюд дефолтным.
4. Залогиниться под обычным пользователем, в каждой паре блюд выбрать недефолтное.
5. Нажать кнопку "Сбросить" => по Network видим, что подряд уходит 3 одинаковых запроса запроса. В отчете каждое из блюд указано 3 раза.
