### ISSUE TITLE
Добавить отчеты для Саши Афанасьева

### ISSUE THREAD

**Issue by snop-snov** [Restream/obeder#29]
Выяснить требования у Саши, написать их сюда

**Comment by igtulm** [comment]
В админке должна быть возможность выгрузки отчета за месяц в виде Excel-таблицы, которая должна содержать следующую информацию:
1) Указан месяц/год сформированного отчета (думаю, еще следует добавить дату выгрузки отчета)
2) В шапке: 
  2.1) ФИО сотрудника, 
  2.2) числа месяца (от 1 до N),
  2.3) суммарное количество обедов для текущего сотрудника;
3) После данных по каждому сотруднику указывается суммарное количество обедов по компании  - ИТОГО.

Выходные дни отмечены красным бэкграундом (весь столбик).
В данных по каждому сотруднику за каждый день у Саши в отчете ставится единичка если сотрудник ест. Если ничего нет - ничего не пишется соответственно.

**Comment by igtulm** [comment]
![image](https://cloud.githubusercontent.com/assets/16452917/24754086/134c2bae-1ae6-11e7-963b-e00c5091db02.png)

**Comment by mkalmykov** [comment]
#70

**Comment by igtulm** [comment]
Недорефакторинг:
  def column_widths
    col_widths = [NAME_COLUMN_WIDTH]
    9.times { col_widths << ONE_SIGN_DAY_COLUMN_WIDTH }
    (report_width - 11).times { col_widths << TWO_SIGN_DAY_COLUMN_WIDTH }
    col_widths << TOTAL_COLUMN_WIDTH
  end

9 количество single-signed дней в месяце от 1 до 9. 
11 = это 9 этих дней + колонка ФИО + колонка суммы

Как вариант можно пробегаться по всем дням в месяце, которые получим методом all_days_in_month, проверить strlen и тернарным выставить ширину. Либо вводить константы.
