### ISSUE TITLE
Ем/не ем на каждый день

### ISSUE THREAD

**Issue by paranta** [Restream/obeder#6]
Иногда уезжаешь на день-два в неделю, и сразу точно это знаешь. Чтобы не переключать посреди недели, было бы хорошо сделать отдельный индикатор для каждого дня.

**Comment by alexander37137** [comment]
Предлагаю впилить календарик куда можно натыкать дни когда нееш

**Comment by igtulm** [comment]
https://github.com/Restream/obeder/pull/26
