### ISSUE TITLE
Прикрутить возможность загружать картинки для блюд

### ISSUE THREAD

**Issue by snop-snov** [Restream/obeder#64]
https://github.com/carrierwaveuploader/carrierwave
https://github.com/minimagick/minimagick

**Comment by mikhkonkov** [comment]
вот еще один гем https://github.com/refile/refile

**Comment by snop-snov** [comment]
можно и refile посмотреть, на вид он более простой и менее популярный чем carrierwave

**Comment by mkalmykov** [comment]
#68
